  { text: "Why can't I sleep at night?" },
  { text: "I got 99 problems but _ ain't one." },
  { text: "What's a girl's best friend?" },
  { text: "What's that smell?" },
  { text: "This is the way the world ends. Not with a bang but with _." },
  { text: "What is Batman's guilty pleasure?" },
  { text: "TSA guidelines now prohibit _ on airplanes." },
  { text: "What ended my last relationship?" },
  { text: "MTV's new reality show features eight washed-up celebrities living with _." },
  { text: "I drink to forget _." },
  { text: "I'm sorry, Professor, but I couldn't complete my homework because of _." },
  { text: "Alternative medicine is now embracing the curative powers of _." },
  { text: "What's that sound?" },
  { text: "What's the next Happy Meal&reg; toy?" },
  { text: "It's a pity that kids these days are all getting involved with _." },
  { text: "In the new Disney Channel Original Movie, Hannah Montana struggles with _ for the first time." },
  { text: "_. That's how I want to die." },
  { text: "What does Dick Cheney prefer?" },
  { text: "What's the most emo?" },
  { text: "Instead of coal, Santa now gives the bad children _." },
  { text: "Next from J.K. Rowling: Harry Potter and the Chamber of _." },
  { text: "A romantic, candlelit dinner would be incomplete without _." },
  { text: "White people like _." },
  { text: "_. Betcha can't have just one!" },
  { text: "War! What is it good for?" },
  { text: "BILLY MAYS HERE FOR _." },
  { text: "_. High five, bro." },
  { text: "During sex, I like to think about _." },
  { text: "What did I bring back from Mexico?" },
  { text: "What are my parents hiding from me?" },
  { text: "What will always get you laid?" },
  { text: "What would grandma find disturbing, yet oddly charming?" },
  { text: "What did the U.S. airdrop to the children of Afghanistan?" },
  { text: "What helps Obama unwind?" },
  { text: "What's there a ton of in heaven?" },
  { text: "Major League Baseball has banned _ for giving players an unfair advantage." },
  { text: "When I am a billionaire, I shall erect a 50-foot statue to commemorate _." },
  { text: "What's the new fad diet?" },
  { text: "When I am the President of the United States, I will create the Department of _." },
  { text: "_. It's a trap!" },
  { text: "How am I maintaining my relationship status?" },
  { text: "What will I bring back in time to convince people that I am a powerful wizard?" },
  { text: "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _." },
  { text: "Coming to Broadway this season, _: The Musical." },
  { text: "What's my secret power?" },
  { text: "What gives me uncontrollable gas?" },
  { text: "But before I kill you, Mr. Bond, I must show you _." },
  { text: "What never fails to liven up the party?" },
  { text: "What am I giving up for Lent?" },
  { text: "What do old people smell like?" },
  { text: "The class field trip was completely ruined by _." },
  { text: "When Pharaoh remained unmoved, Moses called down a plague of _." },
  { text: "I do not know with which weapons World War III will be fought, but World War IV will be fought with _." },
  { text: "What's Teach for America using to inspire inner city students to succeed?" },
  { text: "In Michael Jackson's final moments, he thought about _." },
  { text: "Why do I hurt all over?" },
  { text: "Studies show that lab rats navigate mazes 50% faster after being exposed to _." },
  { text: "Why am I sticky?" },
  { text: "What's my anti-drug?" },
  { text: "And the Academy Award for _ goes to _." },
  { text: "For my next trick, I will pull _ out of _." },
  { text: "_: Good to the last drop." },
  { text: "What did Vin Diesel eat for dinner?" },
  { text: "_: kid-tested, mother-approved." },
  { text: "What gets better with age?" },
  { text: "I never truly understood _ until I encountered _." },
  { text: "Rumor has it that Vladimir Putin's favorite delicacy is _ stuffed with _." },
  { text: "Lifetime&reg; presents _, the story of _." },
  { text: "Make a haiku." },
  { text: "In M. Night Shyamalan's new movie, Bruce Willis discovers that _ had really been _ all along." },
  { text: "_ is a slippery slope that leads to _." },
  { text: "In a world ravaged by _, our only solace is _." },
  { text: "That's right, I killed _. How, you ask? _." },
  { text: "When I was tripping on acid, _ turned into _." },
  { text: "_ + _ = _." },
  { text: "What's the next superhero/sidekick duo?" },
  { text: "Dear Abby, I'm having some trouble with _ and would like your advice." },
  { text: "After the earthquake, Sean Penn brought _ to the people of Haiti." },
  { text: "In L.A. County Jail, word is you can trade 200 cigarettes for _." },
  { text: "Maybe she's born with it. Maybe it's _." },
  { text: "Life for American Indians was forever changed when the White Man introduced them to _." },
  { text: "Next on ESPN2, the World Series of _." },
  { text: "Step 1: _. Step 2: _. Step 3: Profit." },
  { text: "Here is the church. Here is the steeple. Open the doors. And there is _." },
  { text: "How did I lose my virginity?" },
  { text: "During his childhood, Salvador Dal&iacute; produced hundreds of paintings of _." },
  { text: "In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?" },
  { text: "What don't you want to find in your Kung Pao chicken?" },
  { text: "The Smithsonian Museum of Natural History has just opened an exhibit on _." },
  { text: "Daddy, why is Mommy crying?" },
